#!/usr/bin/env bash

#############
### plate ###
#############

S_PATH="$(readlink -f $0)"
S_NAME="$(basename $S_PATH)"
S_DIR="$(dirname $S_PATH)"
F_DIR="$S_DIR/functions"
T_DEF="$S_DIR/templates"
T_DIR="$HOME/.$S_NAME"

for _ in $F_DIR/*
do
    source "$_"
done

main() {

    if [[ ! -d "$T_DIR" ]]
    then cp -r "$T_DEF" "$T_DIR"
    fi

    if [[ $# -eq 0 ]]
    then
        err "'$S_NAME -h' for more info"
    else

        OPTIND=0
        while getopts ':elop:stx:' opt
        do

           case $opt in
               e)EDIT=1;;
               l)T_LIST=1;;
               o)WRITE=1;;
               p)PERM=$OPTARG;;
               s)SILEXT=1;;
               t)T_CAT=1;;
               x)EXT="$OPTARG";;
               *)helpout;;
           esac

       done
        shift $((OPTIND-1))

        if [[ $T_CAT -eq 1 ]]
        then
            print_template_contents $@
        fi

        if [[ $T_LIST -eq 1 ]]
        then
            list_known_templates
        fi

        run_core_loop $@

    fi

}

main $@
